import { describe, it, expect } from "vitest";
import type { HomePageAttributes } from "../../types/home-page";

describe("home-page types", () => {
  it("HomePageAttributes should have all required fields", () => {
    const home: HomePageAttributes = {
      id: 1,
      documentId: "doc-home",
      intro: "Hola, soy",
      title: "Carlos Castañeda",
      subtitle: "carloscndev",
      content: "<p>Intro paragraph</p>",
      avatarDefault: {
        id: 1,
        documentId: "avatar-1",
        name: "hello.webp",
        alternativeText: null,
        caption: null,
        focalPoint: null,
        width: 1920,
        height: 2176,
        formats: {},
        hash: "hello_abc",
        ext: ".webp",
        mime: "image/webp",
        size: 100,
        url: "/uploads/hello_abc.webp",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2024-01-01T00:00:00.000Z",
        updatedAt: "2024-01-01T00:00:00.000Z",
        publishedAt: "2024-01-01T00:00:00.000Z",
      },
      avatarRunning: {
        id: 2,
        documentId: "avatar-2",
        name: "running.webp",
        alternativeText: null,
        caption: null,
        focalPoint: null,
        width: 1920,
        height: 2176,
        formats: {},
        hash: "running_abc",
        ext: ".webp",
        mime: "image/webp",
        size: 120,
        url: "/uploads/running_abc.webp",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2024-01-01T00:00:00.000Z",
        updatedAt: "2024-01-01T00:00:00.000Z",
        publishedAt: "2024-01-01T00:00:00.000Z",
      },
      avatarReading: {
        id: 3,
        documentId: "avatar-3",
        name: "reading.webp",
        alternativeText: null,
        caption: null,
        focalPoint: null,
        width: 1920,
        height: 2176,
        formats: {},
        hash: "reading_abc",
        ext: ".webp",
        mime: "image/webp",
        size: 80,
        url: "/uploads/reading_abc.webp",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2024-01-01T00:00:00.000Z",
        updatedAt: "2024-01-01T00:00:00.000Z",
        publishedAt: "2024-01-01T00:00:00.000Z",
      },
      avatarVideogames: {
        id: 4,
        documentId: "avatar-4",
        name: "playing.webp",
        alternativeText: null,
        caption: null,
        focalPoint: null,
        width: 1920,
        height: 2176,
        formats: {},
        hash: "playing_abc",
        ext: ".webp",
        mime: "image/webp",
        size: 130,
        url: "/uploads/playing_abc.webp",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2024-01-01T00:00:00.000Z",
        updatedAt: "2024-01-01T00:00:00.000Z",
        publishedAt: "2024-01-01T00:00:00.000Z",
      },
      createdAt: "2024-01-01T00:00:00.000Z",
      updatedAt: "2024-01-01T00:00:00.000Z",
      publishedAt: "2024-01-01T00:00:00.000Z",
      locale: "es",
    };
    expect(home.intro).toBe("Hola, soy");
    expect(home.title).toBe("Carlos Castañeda");
    expect(home.avatarDefault.url).toContain("hello");
    expect(home.avatarRunning.url).toContain("running");
    expect(home.avatarReading.url).toContain("reading");
    expect(home.avatarVideogames.url).toContain("playing");
    expect(home.documentId).toBe("doc-home");
  });
});
